name: Check F1 Data Update

on:
  # Schedule to run (e.g., every 30 minutes)
  # Use https://crontab.guru to help define your cron schedule
  schedule:
    - cron: '30 1 27 10 *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_for_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest race pitstops data
        run: python pitstop.py

      - name: Commit & push changes if any
        run: |
          # configure Git for the bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # only commit if there are unstaged changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: update F1 pitstop data [ci skip]"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes detected; nothing to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
